import type { Metadata } from "next";
import "./globals.css"; // Pastikan font diatur di file CSS
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ELaven Zoom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          layout: {
            logoImageUrl: '/icons/logo.svg',
            socialButtonsVariant: 'iconButton'
          },
          variables: {
            colorText: '#ffff',
            colorPrimary: '#0E78F9',
            colorBackground: '#1c1f2e',
            colorInputBackground: '#252a41',
            colorInputText: '#fff'
          }
        }}
      >
        <body className={`${inter.className} bg-dark-2 `}> {/* Hilangkan referensi ke geistSans dan geistMono */}
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
