import type { Metadata } from "next";
import "./globals.css"; // Pastikan font diatur di file CSS
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ELaven Zoom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark-2 `}> {/* Hilangkan referensi ke geistSans dan geistMono */}
        {children}
      </body>
    </html>
  );
}
